import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import { TeamProvider } from "./context/TeamContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Business Point",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TeamProvider>
          <Navbar />
          {children}
          <Footer />
        </TeamProvider>
      </body>
    </html>
  );
}
